import "server-only";
import type {Route} from "@/lib/eligibility/questions-v1";
import {knowledgeStatus} from "./status";
import {pluginKnowledgeFor} from "./plugin";
export {knowledgeStatus} from "./status";
const notes:Record<Route,string[]>={
 "digital-technology":["Independent recognition in the last five years is mandatory. Activities are prompts to identify evidence, not automatic qualification.","Choose at least two distinct additional categories: innovation, contribution outside work, significant product-company impact, or academic research. Several activities within one category still count as one category.","There is no general £30,000 salary threshold for technology endorsement. Salary must be assessed in context and does not replace recognition or the other requirements.","A Master's or PhD distinction alone does not establish the technology research criterion; use qualifying research and peer or expert recognition.","Exceptional promise is usually associated with fewer than five years in technology, not a rigid limit on seniority or total career length.","Recommendation letters need three established technology experts, each familiar with the applicant's work for at least 12 months. Distinct evidence and document limits still matter."],
 "design":["This check covers the DBA design-industry pathway; fashion, architecture and other arts disciplines need their own route criteria.","The route considers professional practice, international work and an established or developing track record. The endorsing body assesses the quality and significance of the work.","At least two qualifying evidence categories are needed: media recognition, international prizes, and appearances or exhibitions. Talent and promise have different country and award thresholds.","Recommendations include two established expert organisations, with at least one in the UK, plus a third expert organisation or individual who has worked with the applicant."],
 "academia-research":["Keep the appointment, approved fellowship, UKRI endorsed-funder and peer-review pathways separate. One pathway's requirements must not be imposed on another.","Peer review requires active research, an eligible discipline, a PhD or equivalent experience and leadership or potential. Promise also considers early career stage.","The £30,000 threshold in the UKRI pathway concerns the grant, not the applicant's salary. Check grant duration, approved funder and host, time commitment and contract term independently.","A qualifying appointment needs the accepted role, appropriate duties and qualifications, recruitment evidence and HR documentation. A qualifying fellowship must be on the approved list and within the relevant five-year period."],
};
export function knowledgeFor(route:Route){return { ...knowledgeStatus,route,notes:notes[route],plugin:pluginKnowledgeFor(route) };}
