import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import { redirect } from "next/navigation";
import { z } from "zod";
import { authClient,verifiedUser } from "@/lib/supabase/server";
import { PendingAssessment } from "@/components/dashboard/account-actions";
import { RequestList } from "@/components/dashboard/request-list";
import type { EligibilityResult } from "@/lib/eligibility/evaluate";
export const metadata={title:"Your dashboard"};
export default async function DashboardPage({searchParams}:{searchParams:Promise<{assessment?:string}>}){
 const user=await verifiedUser();if(!user)redirect("/login");const params=await searchParams;if(params.assessment&&z.uuid().safeParse(params.assessment).success)redirect(`/dashboard/reports?assessment=${params.assessment}`);const db=await authClient();
 const [assessment,applications,active,chats]=await Promise.all([db.from("assessments").select("id,result,created_at",{count:"exact"}).eq("user_id",user.id).order("created_at",{ascending:false}).limit(1),db.from("service_applications").select("id,service,status,decision,created_at",{count:"exact"}).eq("user_id",user.id).order("created_at",{ascending:false}).limit(4),db.from("service_applications").select("id",{count:"exact",head:true}).eq("user_id",user.id).in("status",["submitted","in_review","awaiting_information","accepted"]),db.from("grace_conversations").select("id",{count:"exact",head:true}).eq("user_id",user.id)]);
 const latest=assessment.data?.[0];const result=latest?.result as EligibilityResult|undefined;const raw=user.user_metadata?.full_name;const name=typeof raw==="string"?raw.trim().split(/\s+/)[0]:"there";
 return <><div className="workspace-page-heading"><div><p className="eyebrow">YOUR TALENT. YOUR NEXT CHAPTER.</p><h1>Welcome back, {name}.</h1><p>A clear view of where you are. Everything you need to move forward.</p></div><Link className="button button-dark" href="/dashboard/services">Explore support <span><UiIcon name="arrow-up-right" /></span></Link></div><PendingAssessment/>
 <section className="workspace-stats" aria-label="Your progress"><Link href="/dashboard/reports"><span>Latest readiness score</span><strong>{assessment.error?"—":result?result.score??"Review":"—"}{result?.score!==null&&result&&<small>/100</small>}</strong><small>{result?.routeName??"Take your first eligibility check"} <UiIcon name="arrow-up-right" /></small></Link><Link href="/dashboard/requests"><span>Active requests</span><strong>{active.error?"—":active.count??0}</strong><small>{applications.error?"Currently unavailable":`${applications.count??0} requests in your account`} <UiIcon name="arrow-up-right" /></small></Link><Link href="/dashboard/reports"><span>Eligibility reports</span><strong>{assessment.error?"—":assessment.count??0}</strong><small>Your scores & next steps <UiIcon name="arrow-up-right" /></small></Link><Link href="/dashboard/grace-ai"><span>Grace AI conversations</span><strong>{chats.error?"—":chats.count??0}</strong><small>Coming soon · Saved reports in My reports</small></Link></section>
 <div className="workspace-overview-grid"><section className="workspace-panel next-step-panel"><p className="eyebrow">YOUR NEXT STEP</p><h2>{result?result.headline:"Let’s find your starting point."}</h2><p>{result?result.recommendationReason:"Explore your route, understand the evidence you need and get a personalised readiness report."}</p><div className="report-actions"><Link className="button button-gold" href={latest?`/dashboard/reports?assessment=${latest.id}`:"/dashboard/eligibility"}>{latest?"Open my report":"Check my eligibility"} <UiIcon name="arrow-up-right" /></Link><Link className="text-link" href="/dashboard/services/full-support">Explore full support <UiIcon name="arrow-up-right" /></Link></div><p className="fine-print">A readiness score reflects your answers. It is not a visa decision or guarantee.</p></section><section className="workspace-ai-card"><span className="ai-orb" aria-hidden="true">✦</span><div><span className="ai-pill">GRACE AI · COMING SOON</span><h2>Your AI preparation assistant.<br/>Coming soon.</h2><p>Soon, you’ll be able to discuss your experience, explore evidence gaps and leave with a practical plan.</p><Link className="button button-outline" href="/dashboard/grace-ai">Learn more <UiIcon name="arrow-up-right" /></Link></div></section></div>
 <section className="workspace-panel"><div className="panel-heading"><div><p className="eyebrow">KEEP THINGS MOVING</p><h2>Your recent requests</h2></div><Link className="text-link" href="/dashboard/requests">View all requests <UiIcon name="arrow-up-right" /></Link></div>{applications.error?<p className="form-notice">We couldn’t load your requests right now. Your existing assessments are still available.</p>:applications.data?.length?<RequestList requests={applications.data}/>:<div className="workspace-empty"><span aria-hidden="true"><UiIcon name="arrow-up-right" /></span><h3>Your next step starts here.</h3><p>Submit your documents for review or apply for full support. Track everything in this space.</p><div className="report-actions"><Link className="button button-dark" href="/dashboard/services/document-review">Request document review</Link><Link className="button button-outline" href="/dashboard/services/full-support">Apply for full support</Link></div></div>}</section>
 </>;
}
