import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import {z} from "zod";
import {requireAdmin} from "@/lib/applications/access";
import {adminClient} from "@/lib/supabase/server";
import {dateLabel,pageNumber,userLabels} from "@/lib/admin/data";
import {routes} from "@/lib/eligibility/questions";
export const metadata={title:"Admin · Eligibility checks"};
export default async function Assessments({searchParams}:{searchParams:Promise<{page?:string;route?:string;user?:string}>}){await requireAdmin();const p=await searchParams;const page=pageNumber(p.page);const route=routes.some(r=>r.id===p.route)?p.route!:"all";const user=z.uuid().safeParse(p.user).success?p.user:undefined;let query=adminClient().from("assessments").select("id,user_id,route,result,rules_version,created_at",{count:"exact"});if(route!=="all")query=query.eq("route",route);if(user)query=query.eq("user_id",user);const{data,error,count}=await query.order("created_at",{ascending:false}).range((page-1)*20,page*20-1);const labels=await userLabels((data??[]).map(a=>a.user_id));const href=(n:number)=>`/admin/assessments?${new URLSearchParams({page:String(n),route,...(user?{user}:{})})}`;
 return <><div className="workspace-page-heading"><div><p className="eyebrow">UNDERSTAND EACH CLIENT’S STARTING POINT</p><h1>Eligibility checks</h1><p>See who completed a check, their readiness score, answers and recommended next steps.</p></div><span className="request-status">{error?"Unavailable":`${count??0} saved checks`}</span></div><form className="workspace-filters">{user&&<input type="hidden" name="user" value={user}/>}<label>Route<select name="route" defaultValue={route}><option value="all">All routes</option>{routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="button button-outline">Filter checks</button>{user&&<><Link href={`/admin/users/${user}`} className="text-link">Client profile</Link><Link href="/admin/assessments" className="text-link">Show all users</Link></>}</form><section className="workspace-panel">{error?<p className="form-error">Eligibility activity is currently unavailable.</p>:<><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Client</th><th>Route / pathway</th><th>Readiness score</th><th>Completed</th><th>Details</th></tr></thead><tbody>{data?.map(a=><tr key={a.id}><td><Link href={`/admin/users/${a.user_id}`}><strong>{labels[a.user_id]?.name}</strong><span>{labels[a.user_id]?.email}</span></Link></td><td>{a.result.routeName}<span>{a.result.pathway}</span></td><td><strong>{a.result.score===null?"Not scored":`${a.result.score}/100`}</strong><span>{a.result.headline}</span></td><td>{dateLabel(a.created_at)}</td><td><Link href={`/admin/assessments/${a.id}`}>View answers <UiIcon name="arrow-up-right" /></Link></td></tr>)}</tbody></table></div>{!data?.length&&<p>No saved checks match these filters.</p>}<div className="workspace-pagination">{page>1&&<Link href={href(page-1)}><UiIcon name="arrow-left" /> Previous</Link>}<span>Page {page}</span>{page*20<(count??0)&&<Link href={href(page+1)}>Next <UiIcon name="arrow-right" /></Link>}</div></>}</section><p className="fine-print">Counts cover completed checks saved to verified accounts. Abandoned anonymous questionnaires are not stored or included.</p></>;
}
