import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import { redirect } from "next/navigation";
import { authClient,verifiedUser } from "@/lib/supabase/server";
import { statusLabels } from "@/lib/applications/types";
import { RequestList } from "@/components/dashboard/request-list";
export const metadata={title:"My requests"};
export default async function RequestsPage({searchParams}:{searchParams:Promise<{status?:string;service?:string;page?:string}>}){
 const user=await verifiedUser();if(!user)redirect("/login?next=%2Fdashboard%2Frequests");const params=await searchParams;const page=Math.min(10000,Math.max(1,parseInt(params.page??"1")||1));const status=params.status&&Object.hasOwn(statusLabels,params.status)?params.status:"all";const service=["document-review","full-support"].includes(params.service??"")?params.service!:"all";const db=await authClient();let query=db.from("service_applications").select("id,service,status,decision,created_at",{count:"exact"}).eq("user_id",user.id);if(status!=="all")query=query.eq("status",status);if(service!=="all")query=query.eq("service",service);const result=await query.order("created_at",{ascending:false}).range((page-1)*15,page*15-1);const url=(p:number)=>`/dashboard/requests?${new URLSearchParams({status,service,page:String(p)})}`;
 return <><div className="workspace-page-heading"><div><p className="eyebrow">YOUR SUPPORT, IN ONE PLACE</p><h1>My requests</h1><p>Follow your application, manage documents and payments, and read Grace’s feedback.</p></div><Link className="button button-dark" href="/dashboard/services">New request <UiIcon name="arrow-up-right" /></Link></div><form className="workspace-filters"><label>Service<select name="service" defaultValue={service}><option value="all">All services</option><option value="document-review">Document review</option><option value="full-support">Full support</option></select></label><label>Status<select name="status" defaultValue={status}><option value="all">All statuses</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className="button button-outline">Apply filters</button>{(status!=="all"||service!=="all")&&<Link className="text-link" href="/dashboard/requests">Clear</Link>}</form><section className="workspace-panel">{result.error?<div className="workspace-empty"><h2>Your requests couldn’t be loaded.</h2><p>Please try again shortly. You can still explore services and view your eligibility reports.</p><Link className="button button-outline" href="/dashboard/requests">Try again</Link></div>:result.data?.length?<><div className="panel-heading"><h2>{result.count} {result.count===1?"request":"requests"}</h2><span className="fine-print">Most recent first</span></div><RequestList requests={result.data}/><div className="workspace-pagination">{page>1&&<Link href={url(page-1)}><UiIcon name="arrow-left" /> Previous</Link>}<span>Page {page}</span>{page*15<(result.count??0)&&<Link href={url(page+1)}>Next <UiIcon name="arrow-right" /></Link>}</div></>:<div className="workspace-empty"><h2>{status!=="all"||service!=="all"?"No requests match these filters.":"Your requests will live here."}</h2><p>Start a document review or full-support application. Saved drafts appear here too, so you can pick up where you left off.</p><Link className="button button-gold" href="/dashboard/services">Explore services <UiIcon name="arrow-up-right" /></Link></div>}</section></>;
}
