"use client";
import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState,type ReactNode } from "react";
import { Brand } from "@/components/brand";
import { SignOutButton } from "./account-actions";
const navigation=[{href:"/dashboard",label:"Overview",icon:"overview"},{href:"/dashboard/requests",label:"My requests",icon:"requests"},{href:"/dashboard/grace-ai",label:"Grace AI",icon:"chat"},{href:"/dashboard/eligibility",label:"Eligibility checker",icon:"check"},{href:"/dashboard/reports",label:"My reports",icon:"reports"},{href:"/dashboard/services",label:"Services & resources",icon:"services"}];
export function WorkspaceIcon({name}:{name:string}){const paths:Record<string,ReactNode>={overview:<><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,requests:<><path d="M8 4H5a2 2 0 0 0-2 2v14h18V6a2 2 0 0 0-2-2h-3"/><rect x="8" y="2" width="8" height="5" rx="2"/><path d="M7 12h10M7 16h6"/></>,chat:<path d="M21 11a8 8 0 0 1-8 8H7l-4 3V11a9 9 0 0 1 18 0ZM7 10h10M7 14h6"/>,check:<><circle cx="12" cy="12" r="9"/><path d="m7 12 3 3 7-7"/></>,reports:<><path d="M14 2H5v20h14V7Z"/><path d="M14 2v5h5M8 12h8M8 16h6"/></>,services:<><path d="m12 3 9 5-9 5-9-5ZM3 12l9 5 9-5M3 16l9 5 9-5"/></>};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.overview}</svg>;}
export function WorkspaceShell({children,name,email,admin}:{children:ReactNode;name:string;email:string;admin:boolean}){
 const pathname=usePathname();const [menu,setMenu]=useState(false);const active=(href:string)=>href==="/dashboard"?pathname===href:pathname.startsWith(href);const title=navigation.find(n=>active(n.href))?.label??"Your account";const initials=name.split(/\s+/).map(n=>n[0]).slice(0,2).join("").toUpperCase();
 return <div className="workspace"><a className="skip-link" href="#workspace-main">Skip to content</a><aside className={`workspace-sidebar${menu?" is-open":""}`}><div className="workspace-brand"><Brand/></div><nav aria-label="Dashboard">{navigation.map(n=><Link key={n.href} href={n.href} aria-current={active(n.href)?"page":undefined} onClick={()=>setMenu(false)}><WorkspaceIcon name={n.icon}/><span>{n.label}</span>{n.icon==="chat"&&<small>Coming soon</small>}</Link>)}</nav><div className="sidebar-help"><span className="sidebar-star" aria-hidden="true">✦</span><strong>A little clarity goes a long way.</strong><p>Explore your route and understand your next steps.</p><Link href="/dashboard/eligibility" onClick={()=>setMenu(false)}>Check my eligibility <UiIcon name="arrow-up-right" /></Link></div><div className="sidebar-bottom">{admin&&<Link href="/admin">Team admin <UiIcon name="arrow-up-right" /></Link>}<Link href="/resources">Free resources <UiIcon name="arrow-up-right" /></Link><Link href="/">Back to website <UiIcon name="arrow-up-right" /></Link><Link href="/dashboard/account" onClick={()=>setMenu(false)}>Account & support</Link><SignOutButton/></div></aside><div className="workspace-body"><header className="workspace-topbar"><button className="workspace-menu" aria-label={menu?"Close navigation":"Open navigation"} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?"✕":"☰"}</button><div className="workspace-breadcrumb"><span>My workspace</span><span aria-hidden="true">/</span><strong>{title}</strong></div>{admin&&<Link href="/admin" className="profile-admin-button">Admin <UiIcon name="arrow-up-right" /></Link>}<Link href="/dashboard/account" className="workspace-user" aria-label={`Account for ${name}`}><span className="workspace-avatar">{initials||"LG"}</span><span><strong>{name}</strong><small>{email}</small></span></Link></header><main id="workspace-main" className={`workspace-content${pathname.startsWith("/dashboard/grace-ai")?" workspace-chat-page":""}`}>{children}</main></div></div>;
}
