"use client";
import Link from "next/link";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { routes,sources,type Route } from "@/lib/eligibility/questions";
import type { Conversation } from "@/lib/grace-ai/schema";
type Assessment={id:string;route:string;created_at:string};
type History={id:string;route:string;created_at:string};
const starters=[{title:"Where do I stand?",text:"Help me understand whether my experience fits the Global Talent route."},{title:"Find my evidence gaps",text:"Help me identify gaps in my evidence and what I should work on next."},{title:"Plan my next steps",text:"Help me create a practical plan for preparing my endorsement application."}];
export function GraceChat({initial,assessments,available,preferredAssessment,history,historyPage,hasMore,historyError}:{initial:Conversation|null;assessments:Assessment[];available:boolean;preferredAssessment?:string;history:History[];historyPage:number;hasMore:boolean;historyError:boolean}){
 const seeded=assessments.find(a=>a.id===preferredAssessment);const [conversation,setConversation]=useState(initial);const [id]=useState(()=>initial?.id??crypto.randomUUID());const [route,setRoute]=useState<Route>((initial?.route??seeded?.route??"digital-technology") as Route);const [assessment,setAssessment]=useState(initial?.assessment_id??seeded?.id??"");const [message,setMessage]=useState("");const [consent,setConsent]=useState(Boolean(initial));const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [started,setStarted]=useState(Boolean(initial));const [showPlan,setShowPlan]=useState(false);const [showHistory,setShowHistory]=useState(false);const retry=useRef<{message:string;id:string}|null>(null);const scroll=useRef<HTMLDivElement>(null);const composer=useRef<HTMLTextAreaElement>(null);const router=useRouter();
 useEffect(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;},[conversation,busy]);
 async function send(event:FormEvent){event.preventDefault();if(busy||!available||!consent||!message.trim())return;setBusy(true);setError("");setStarted(true);const requestId=retry.current?.message===message?retry.current.id:crypto.randomUUID();retry.current={message,id:requestId};try{const response=await fetch("/api/grace-ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,requestId,route,assessmentId:assessment||null,message,consent})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to send your message.");setConversation(data);setMessage("");retry.current=null;window.history.replaceState(null,"",`/dashboard/grace-ai?conversation=${id}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);composer.current?.focus();}}
 const atLimit=(conversation?.turns.length??0)>=20;const routeName=routes.find(r=>r.id===route)?.name;const historyHref=(page:number)=>`/dashboard/grace-ai?${new URLSearchParams({page:String(page),...(conversation?{conversation:id}:{})})}`;
 return <div className="chat-workspace"><aside className={`chat-history${showHistory?" visible":""}`}><div className="chat-history-title"><strong>Your conversations</strong><button className="chat-mobile-close" onClick={()=>setShowHistory(false)} aria-label="Close conversation history">✕</button></div><a className="chat-new" href="/dashboard/grace-ai">＋ New conversation</a><p className="chat-history-label">RECENT DISCUSSIONS</p>{historyError?<p className="fine-print">History is temporarily unavailable.</p>:!history.length?<p className="fine-print">Your conversations will appear here. Come back whenever you need a little clarity.</p>:history.map(c=><Link href={`/dashboard/grace-ai?conversation=${c.id}`} key={c.id} onClick={()=>setShowHistory(false)} aria-current={c.id===conversation?.id?"page":undefined}><span aria-hidden="true">↳</span><div><strong>{routes.find(r=>r.id===c.route)?.name??c.route}</strong><small>{new Date(c.created_at).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}</small></div></Link>)}{(historyPage>1||hasMore)&&<div className="chat-history-pages">{historyPage>1&&<Link href={historyHref(historyPage-1)}>← Newer</Link>}{hasMore&&<Link href={historyHref(historyPage+1)}>Older →</Link>}</div>}<div className="chat-history-footer"><Link href="/dashboard/reports">All my reports ↗</Link><p>Your conversations are private to your account and authorised team members.</p></div></aside>
 <section className="chat-room"><header className="chat-room-header"><button className="chat-history-toggle" onClick={()=>setShowHistory(!showHistory)} aria-expanded={showHistory}>History</button><span className="chat-grace-avatar" aria-hidden="true">✦</span><div><h1>Grace AI</h1><p>AI preparation assistant · {routeName}</p></div><button className={`chat-plan-toggle${showPlan?" selected":""}`} onClick={()=>setShowPlan(!showPlan)} aria-expanded={showPlan}>My action plan <span>↗</span></button></header>
 {!available&&<div className="chat-availability" role="status">Grace AI is being prepared. You can <Link href="/dashboard/eligibility">use the eligibility checker</Link> or <a href="https://nestuge.com/8xxydaxvz" target="_blank" rel="noreferrer">book a consultation</a> while it’s getting ready.</div>}
 <div className="chat-transcript" ref={scroll} role="log" aria-label="Conversation with Grace AI" aria-live="polite">
 {!conversation?.turns.length&&!busy?<div className="chat-welcome"><span className="chat-welcome-mark" aria-hidden="true">✦</span><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Big ambitions.<br/>Let’s find your next step.</h2><p>Tell me about your work, your achievements or what’s holding you back. We’ll explore it together.</p><fieldset disabled={started||busy} className="chat-route-choice"><label>Your route<select value={route} onChange={e=>{setRoute(e.target.value as Route);setAssessment("");}}>{routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{assessments.some(a=>a.route===route)&&<label>Use a saved readiness report<select value={assessment} onChange={e=>setAssessment(e.target.value)}><option value="">Start with my experience</option>{assessments.filter(a=>a.route===route).map(a=><option key={a.id} value={a.id}>Assessment · {new Date(a.created_at).toLocaleDateString("en-GB")}</option>)}</select></label>}</fieldset><div className="chat-starters">{starters.map(s=><button key={s.title} disabled={!available} onClick={()=>{setMessage(s.text);composer.current?.focus();}}><strong>{s.title}</strong><span>↗</span></button>)}</div></div>:null}
 {conversation?.turns.map(t=><div key={t.requestId} className="chat-turn"><div className="chat-line from-user"><div className="chat-message"><span>You</span><p>{t.message}</p></div></div><div className="chat-line from-grace"><span className="chat-message-avatar" aria-hidden="true">✦</span><div className="chat-message"><span>Grace AI</span><p>{t.reply}</p></div></div></div>)}{busy&&<div className="chat-turn"><div className="chat-line from-user"><div className="chat-message"><span>You</span><p>{message}</p></div></div><div className="chat-line from-grace"><span className="chat-message-avatar" aria-hidden="true">✦</span><div className="chat-typing" role="status"><i/><i/><i/><span className="sr-only">Grace AI is preparing a response</span></div></div></div>}
 </div>
 <form className="chat-input-area" onSubmit={send}>{!conversation&&<label className="chat-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to OpenAI processing my messages and linked report, and saving this discussion to my account. <Link href="/privacy" target="_blank">Privacy notice</Link></span></label>}{error&&<p className="form-error" role="alert">{error}</p>}{atLimit?<div className="form-notice">You’ve reached the end of this discussion. Download your action plan or <a href="/dashboard/grace-ai">start a new conversation</a>.</div>:<div className="chat-input-box"><label className="sr-only" htmlFor="grace-message">Message Grace AI</label><textarea id="grace-message" ref={composer} rows={2} maxLength={3000} required value={message} onChange={e=>setMessage(e.target.value)} disabled={busy||!available} placeholder="Ask a question, share your experience…" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit();}}}/><button disabled={busy||!available||!consent||!message.trim()} aria-label="Send message">{busy?"…":"↑"}</button></div>}<div className="chat-input-hint"><span>AI guidance · Grace reviews applications personally.</span><span>{message.length?`${message.length}/3,000`:'Enter to send · Shift + Enter for a new line'}</span></div></form>
 </section>
 {showPlan&&<aside className="chat-plan"><div className="panel-heading"><p className="eyebrow">YOUR ACTION PLAN</p><button onClick={()=>setShowPlan(false)} aria-label="Close action plan">✕</button></div><h2>Clarity to take with you.</h2>{conversation?.report?<><p>{conversation.report.summary}</p><h3>Your next steps</h3><ol>{conversation.report.nextSteps.map((s,i)=><li key={i}>{s}</li>)}</ol>{conversation.report.gaps.length>0&&<details><summary>Evidence gaps & questions</summary><ul>{conversation.report.gaps.map((s,i)=><li key={i}>{s}</li>)}</ul></details>}<a className="button button-dark" href={`/api/grace-ai/${id}/report`}>Download report ↓</a><Link className="button button-outline" href={`/dashboard/services/full-support?conversation=${id}`}>Use this for full support ↗</Link></>:<p>Your summary and next steps will appear after your first AI response. Keep talking to add more detail.</p>}<p className="fine-print">This is an AI summary of your information, not Grace’s personal verdict or an endorsement decision.</p><a className="text-link" href={route==="digital-technology"?sources.tech:route==="design"?sources.design:sources.research} target="_blank" rel="noreferrer">Official route guidance ↗</a></aside>}
 </div>;
}
