import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

test("database migration protects ownership, enforces idempotency and reliably leases email jobs", async () => {
  const db = new PGlite();
  try {
    await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      grant usage on schema public,auth to anon,authenticated,service_role;
      grant execute on function auth.uid() to authenticated;
      grant select on auth.users to service_role;`);
    await db.exec(await readFile(new URL("../supabase/migrations/202610010001_eligibility.sql", import.meta.url), "utf8"));
    const owner = crypto.randomUUID(), stranger = crypto.randomUUID(), submission = crypto.randomUUID();
    await db.query("insert into auth.users(id) values($1),($2)", [owner, stranger]);
    await db.exec("set role service_role");
    const params = [owner, submission, "digital-technology", '{"recognition":"yes"}', '{"score":50}', "2026-10-01.1"];
    const saved = await db.query<{ id: string }>("select public.save_eligibility_assessment($1,$2,$3,$4::jsonb,$5::jsonb,$6) as id", params);
    const id = saved.rows[0].id;
    const repeated = await db.query<{ id: string }>("select public.save_eligibility_assessment($1,$2,$3,$4::jsonb,$5::jsonb,$6) as id", params);
    assert.equal(repeated.rows[0].id, id);
    assert.equal((await db.query("select * from result_email_jobs")).rows.length, 1);
    await assert.rejects(db.query("select public.save_eligibility_assessment($1,$2,$3,$4::jsonb,$5::jsonb,$6)", [owner, submission, "design", "{}", "{}", "v1"]), /different answers/);
    await db.exec("reset role; set role authenticated");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [owner]);
    assert.equal((await db.query("select * from assessments")).rows.length, 1);
    assert.equal((await db.query("select status,attempts from result_email_jobs")).rows.length, 1);
    await assert.rejects(db.query("select lease_token from result_email_jobs"), /permission denied/);
    await assert.rejects(db.query("update assessments set result='{}'"), /permission denied/);
    await assert.rejects(db.query("select public.save_eligibility_assessment($1,$2,$3,$4::jsonb,$5::jsonb,$6)", params), /permission denied/);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [stranger]);
    assert.equal((await db.query("select * from assessments")).rows.length, 0);
    assert.equal((await db.query("select status from result_email_jobs")).rows.length, 0);
    await db.exec("reset role; set role anon");
    await assert.rejects(db.query("select * from assessments"), /permission denied/);
    await db.exec("reset role; set role service_role");
    const job = (await db.query<{ id: string }>("select id from result_email_jobs")).rows[0].id;
    const lease = (await db.query<{ lease_token: string }>("select * from claim_result_email($1)", [job])).rows[0].lease_token;
    assert.equal((await db.query("select * from claim_result_email($1)", [job])).rows.length, 0, "a second worker cannot take an active lease");
    await db.query("select finish_result_email($1,$2,false,null,'retry')", [job, lease]);
    assert.equal((await db.query("select * from claim_result_email($1)", [job])).rows.length, 0, "backoff must be respected");
    await db.query("update result_email_jobs set next_attempt_at=now()-interval '1 second' where id=$1", [job]);
    const nextLease = (await db.query<{ lease_token: string }>("select * from claim_result_email($1)", [job])).rows[0].lease_token;
    await db.query("select finish_result_email($1,$2,true,'stale',null)", [job, lease]);
    assert.equal((await db.query<{ status: string }>("select status from result_email_jobs")).rows[0].status, "sending", "stale worker must not overwrite a new lease");
    await db.query("select finish_result_email($1,$2,true,'provider-id',null)", [job, nextLease]);
    assert.equal((await db.query<{ status: string }>("select status from result_email_jobs")).rows[0].status, "sent");
    assert.equal((await db.query("select * from claim_result_email($1)", [job])).rows.length, 0, "acknowledged emails cannot be sent again");
    const expiredAssessment = (await db.query<{ id: string }>("select public.save_eligibility_assessment($1,$2,$3,$4::jsonb,$5::jsonb,$6) as id", [owner, crypto.randomUUID(), ...params.slice(2)])).rows[0].id;
    const expiredJob = (await db.query<{ id: string }>("select id from result_email_jobs where assessment_id=$1", [expiredAssessment])).rows[0].id;
    await db.query("update result_email_jobs set first_attempt_at=now()-interval '24 hours',attempts=1 where id=$1", [expiredJob]);
    assert.equal((await db.query("select * from claim_result_email($1)", [expiredJob])).rows.length, 0, "expired provider idempotency window must not send again");
    const expired = (await db.query<{ status: string; attempts: number }>("select status,attempts from result_email_jobs where id=$1", [expiredJob])).rows[0];
    assert.equal(expired.status, "failed");
    assert.equal(expired.attempts, 5);
    assert.equal((await db.query<{ allowed: boolean }>("select consume_request_limit('test',1,60) as allowed")).rows[0].allowed, true);
    assert.equal((await db.query<{ allowed: boolean }>("select consume_request_limit('test',1,60) as allowed")).rows[0].allowed, false);
    await db.exec("reset role");
    await db.query("delete from auth.users where id=$1", [owner]);
    assert.equal((await db.query("select * from assessments")).rows.length, 0);
    assert.equal((await db.query("select * from result_email_jobs")).rows.length, 0);
  } finally { await db.close(); }
});
