import {test} from "node:test";
import assert from "node:assert/strict";
import reference from "../lib/eligibility/tech-reference.json";
import {questionsFor,questionsForVersion,techCoreQuestions,validAnswer,toggleAnswer,RULES_VERSION,type Route,type Answers} from "../lib/eligibility/questions";
import {evaluate} from "../lib/eligibility/evaluate";
import {validateAnswers} from "../lib/eligibility/schema";
function complete(route:Route,overrides:Answers={}):Answers{
 const defaults:Answers={adult:"yes",prize:"no",company_type:"yes",role_type:"tech_leader",talent_route:"talent",evidence_impact:"speaking|awards",innovation:"strong",outside_work:"mentoring|speaking",significant_contribution:"strong",academics:"published|proof",recommendation_letters:"yes_3",track:"talent",researchPath:"peer",researchRole:"lead",designScope:"listed",stage:"ready",...overrides};let out:Answers={};for(let i=0;i<4;i++){out=Object.fromEntries(questionsFor(route,{...defaults,...out}).map(q=>[q.id,overrides[q.id]??defaults[q.id]??(q.options.some(o=>o.value==="yes")?"yes":q.options[0].value)]));}return out;
}
test("technology has exactly the nine LIVE reference questions, descriptions and choices in order",()=>{
 const current=questionsFor("digital-technology",{});assert.equal(current.length,9);
 assert.deepEqual(current.map(q=>({id:q.id,title:q.title,type:q.type,description:q.help,options:q.options})),reference.map(q=>({id:q.id,title:q.title,type:q.type,description:q.description,options:q.options.map(o=>({value:o.value,label:o.label}))})));
 assert.equal(techCoreQuestions.filter(q=>q.type==="multi").length,3);
 assert.equal(evaluate("digital-technology",complete("digital-technology")).score,100);
 assert.equal(evaluate("digital-technology",complete("digital-technology")).rulesVersion,RULES_VERSION);
});
test("multi-select rejects malformed answers and keeps None exclusive",()=>{const q=techCoreQuestions.find(q=>q.id==="outside_work")!;assert(validAnswer(q,"speaking|mentoring"));for(const v of ["speaking|none","speaking|speaking","invented","speaking|","|speaking"])assert.equal(validAnswer(q,v),false,v);assert.equal(toggleAnswer(q,"speaking|mentoring","none"),"none");assert.equal(toggleAnswer(q,"none","mentoring"),"mentoring");assert.equal(toggleAnswer(q,"speaking|mentoring","speaking"),"mentoring");});
test("salary and degree distinction alone do not qualify as recognition or research",()=>{const a=complete("digital-technology",{evidence_impact:"high_salary",academics:"distinction|proof",innovation:"none",outside_work:"none",significant_contribution:"none"});const r=evaluate("digital-technology",a);assert.equal(r.status,"requirements-gap");assert.equal(r.checks.find(c=>c.id==="evidence_impact")?.credit,0);assert.equal(r.checks.find(c=>c.id==="academics")?.credit,0);assert.match(r.summary,/preliminary/);assert.equal(r.scoreMethod,"profile-nine-v1");});
test("several outside-work activities remain one optional category",()=>{const r=evaluate("digital-technology",complete("digital-technology",{innovation:"none",outside_work:"speaking|mentoring|writing|open_source",significant_contribution:"none",academics:"none"}));assert.equal(r.status,"requirements-gap");assert(r.notes.some(n=>n.includes("1 distinct optional")));});
test("technical work outside a product company is not an automatic exclusion",()=>{const r=evaluate("digital-technology",complete("digital-technology",{company_type:"no"}));assert.notEqual(r.status,"requirements-gap");assert(r.notes.some(n=>n.includes("does not automatically exclude")));assert.equal(evaluate("digital-technology",complete("digital-technology",{company_type:"no",role_type:"biz_leader"})).status,"requirements-gap");});
test("nine-question answers do not invent unasked age, document pack or referee tenure",()=>{const r=evaluate("digital-technology",complete("digital-technology"));assert(!r.checks.some(c=>["adult","techPack","techLetters"].includes(c.id)));assert(r.notes.some(n=>n.includes("does not establish age")));assert.equal(r.recommendedService,"consultation");});
test("direct design and research pathways retain their separate requirements",()=>{assert.equal(evaluate("design",complete("design")).status,"ready-for-review");assert.equal(evaluate("design",complete("design",{designMedia:"no",designAwards:"yes",designExhibitions:"no"})).status,"requirements-gap");assert.equal(evaluate("design",complete("design",{designScope:"fashion"})).score,null);for(const researchPath of ["appointment","fellowship","funded","peer"]){assert.equal(evaluate("academia-research",complete("academia-research",{researchPath})).status,"ready-for-review",researchPath);}assert.equal(evaluate("academia-research",complete("academia-research",{researchPath:"funded",grant:"no"})).status,"requirements-gap");});
test("new submissions reject old fields, forged scores and omissions; historical answers keep their labels",()=>{const a=complete("digital-technology");assert.throws(()=>validateAnswers("digital-technology",{...a,outside_proof:"yes"}),/does not belong/);delete a.outside_work;assert.throws(()=>validateAnswers("digital-technology",a),/Please answer/);assert.throws(()=>evaluate("digital-technology",{...complete("digital-technology"),score:"100"}),/does not belong/);assert(questionsForVersion("digital-technology",{prize:"no",outside_work:"mentoring"},"2026-10-02.2").some(q=>q.id==="outside_proof"));});
