import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { z } from "zod";
import { authClient,verifiedUser } from "@/lib/supabase/server";
import { ResultPanel } from "@/components/dashboard/result-panel";
import type { EligibilityResult } from "@/lib/eligibility/evaluate";
export const metadata={title:"My reports"};
export default async function ReportsPage({searchParams}:{searchParams:Promise<{assessment?:string;page?:string}>}){
 const user=await verifiedUser();if(!user)redirect("/login?next=%2Fdashboard%2Freports");const params=await searchParams;const db=await authClient();
 if(params.assessment){if(!z.uuid().safeParse(params.assessment).success)notFound();const a=await db.from("assessments").select("id,result,created_at").eq("id",params.assessment).eq("user_id",user.id).maybeSingle();if(a.error)throw new Error("Unable to load your report.");if(!a.data)notFound();const email=await db.from("result_email_jobs").select("status,attempts").eq("assessment_id",a.data.id).maybeSingle();return <><Link className="workspace-back" href="/dashboard/reports"><UiIcon name="arrow-left" /> All reports</Link><ResultPanel id={a.data.id} result={a.data.result as EligibilityResult} createdAt={a.data.created_at} email={email.data??null}/></>;}
 const page=Math.min(10000,Math.max(1,parseInt(params.page??"1")||1));const start=(page-1)*12,end=page*12-1;
 const [assessments,chats,verdicts]=await Promise.all([db.from("assessments").select("id,result,created_at",{count:"exact"}).eq("user_id",user.id).order("created_at",{ascending:false}).range(start,end),db.from("grace_conversations").select("id,route,created_at",{count:"exact"}).eq("user_id",user.id).not("report","is",null).order("created_at",{ascending:false}).range(start,end),db.from("service_applications").select("id,service,verdict,created_at",{count:"exact"}).eq("user_id",user.id).neq("verdict","").order("created_at",{ascending:false}).range(start,end)]);
 const pages=Math.ceil(Math.max(assessments.count??0,chats.count??0,verdicts.count??0)/12);
 return <><div className="workspace-page-heading"><div><p className="eyebrow">CLARITY YOU CAN COME BACK TO</p><h1>My reports</h1><p>Your readiness scores, AI discussions and Grace’s personal recommendations.</p></div><Link className="button button-dark" href="/dashboard/eligibility">New eligibility check <UiIcon name="arrow-up-right" /></Link></div><section className="workspace-panel"><div className="panel-heading"><h2>Eligibility reports</h2><span className="fine-print">Your score & action plan</span></div>{assessments.error?<p className="form-notice">Your assessments couldn’t be loaded.</p>:assessments.data?.length?<div className="report-library">{assessments.data.map(a=>{const r=a.result as EligibilityResult;return <article key={a.id}><div className="report-score">{r.score??"—"}<small>{r.score!==null?"/100":"Pathway"}</small></div><div><h3>{r.routeName}</h3><p>{r.headline}</p><small>{new Date(a.created_at).toLocaleDateString("en-GB")}</small></div><div className="report-library-actions"><Link href={`/dashboard/reports?assessment=${a.id}`}>View report <UiIcon name="arrow-up-right" /></Link><a href={`/api/assessments/${a.id}/report`}>Download PDF <UiIcon name="arrow-down" /></a></div></article>;})}</div>:<p>No reports on this page. <Link className="text-link" href="/dashboard/eligibility">Check your eligibility <UiIcon name="arrow-up-right" /></Link></p>}</section><div className="workspace-overview-grid"><section className="workspace-panel"><h2>Grace AI discussions</h2>{chats.error?<p>Discussion reports are currently unavailable.</p>:chats.data?.length?<div className="report-mini-list">{chats.data.map(c=><article key={c.id}><strong>{c.route.replaceAll("-"," ")}</strong><small>{new Date(c.created_at).toLocaleDateString("en-GB")}</small><div><a href={`/api/grace-ai/${c.id}/report`}>Download <UiIcon name="arrow-down" /></a></div></article>)}</div>:<p>Grace AI is coming soon. Your future discussion reports will appear here.</p>}</section><section className="workspace-panel"><h2>Grace’s verdicts</h2>{verdicts.error?<p>Personal review reports are currently unavailable.</p>:verdicts.data?.length?<div className="report-mini-list">{verdicts.data.map(a=><article key={a.id}><strong>{a.service==="document-review"?"Document review":"Full support"}</strong><small>{new Date(a.created_at).toLocaleDateString("en-GB")}</small><div><Link href={`/dashboard/requests/${a.id}`}>View verdict <UiIcon name="arrow-up-right" /></Link><a href={`/api/applications/${a.id}/report`}>Download <UiIcon name="arrow-down" /></a></div></article>)}</div>:<p>When Grace reviews your request, her personal verdict and next steps will appear here.</p>}</section></div>{pages>1&&<div className="workspace-pagination">{page>1&&<Link href={`/dashboard/reports?page=${page-1}`}><UiIcon name="arrow-left" /> Previous</Link>}<span>Page {page} of {pages}</span>{page<pages&&<Link href={`/dashboard/reports?page=${page+1}`}>Next <UiIcon name="arrow-right" /></Link>}</div>}</>;
}
