import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import {notFound} from "next/navigation";
import {z} from "zod";
import {requireAdmin} from "@/lib/applications/access";
import {adminClient} from "@/lib/supabase/server";
import {dateLabel} from "@/lib/admin/data";
import {statusLabels} from "@/lib/applications/types";
export const metadata={title:"Admin · Client activity"};
export default async function UserDetail({params}:{params:Promise<{id:string}>}){await requireAdmin();const{id}=await params;if(!z.uuid().safeParse(id).success)notFound();const db=adminClient();const{data,error}=await db.auth.admin.getUserById(id);if(error||!data.user)notFound();const u=data.user;const[requests,checks,chats]=await Promise.all([db.from("service_applications").select("id,service,status,created_at",{count:"exact"}).eq("user_id",id).order("created_at",{ascending:false}).limit(20),db.from("assessments").select("id,result,created_at",{count:"exact"}).eq("user_id",id).order("created_at",{ascending:false}).limit(20),db.from("grace_conversations").select("id,route,created_at",{count:"exact"}).eq("user_id",id).order("created_at",{ascending:false}).limit(20)]);
 return <><Link className="workspace-back" href="/admin/users"><UiIcon name="arrow-left" /> All users</Link><div className="workspace-page-heading"><div><p className="eyebrow">CLIENT PROFILE</p><h1>{typeof u.user_metadata?.full_name==="string"?u.user_metadata.full_name:"Client"}</h1><p>{u.email} · Joined {dateLabel(u.created_at)}</p></div><a href={`mailto:${u.email}`} className="button button-outline">Email client <UiIcon name="arrow-up-right" /></a></div><section className="workspace-panel"><div className="panel-heading"><h2>Requests ({requests.error?"—":requests.count})</h2></div>{requests.error?<p>Requests could not be loaded.</p>:requests.data?.length?<ul className="admin-activity-items">{requests.data.map(a=><li key={a.id}><Link href={`/admin/applications/${a.id}`}><strong>{a.service==="document-review"?"Document review":"Full support"}</strong><span>{statusLabels[a.status]} · {dateLabel(a.created_at)} <UiIcon name="arrow-up-right" /></span></Link></li>)}</ul>:<p>No service requests yet.</p>}<Link className="text-link" href={`/admin/requests?user=${id}`}>All this user’s requests <UiIcon name="arrow-up-right" /></Link></section><div className="workspace-overview-grid"><section className="workspace-panel"><h2>Eligibility checks ({checks.error?"—":checks.count})</h2>{checks.error?<p>Checks could not be loaded.</p>:checks.data?.length?<ul className="admin-activity-items">{checks.data.map(a=><li key={a.id}><Link href={`/admin/assessments/${a.id}`}><strong>{a.result.routeName}</strong><span>{a.result.score===null?"Pathway review":`${a.result.score}/100`} · {dateLabel(a.created_at)} <UiIcon name="arrow-up-right" /></span></Link></li>)}</ul>:<p>No saved eligibility checks yet.</p>}<Link className="text-link" href={`/admin/assessments?user=${id}`}>All this user’s checks <UiIcon name="arrow-up-right" /></Link></section><section className="workspace-panel"><h2>Grace AI discussions ({chats.error?"—":chats.count})</h2>{chats.error?<p>Discussions could not be loaded.</p>:chats.data?.length?<ul className="admin-activity-items">{chats.data.map(c=><li key={c.id}><Link href={`/admin/grace-ai/${c.id}`}><strong>{c.route.replaceAll("-"," ")}</strong><span>{dateLabel(c.created_at)} <UiIcon name="arrow-up-right" /></span></Link></li>)}</ul>:<p>No AI conversations yet.</p>}<Link className="text-link" href={`/admin/grace-ai?user=${id}`}>All this user’s discussions <UiIcon name="arrow-up-right" /></Link></section></div></>;
}
