import {questionsFor as legacyQuestionsFor,sources,type Route,type Answers,type Option,type Question as LegacyQuestion} from "./questions-v1";
import {knowledgeStatus} from "@/lib/knowledge/status";
import {evidenceHelp} from "@/lib/knowledge/evidence-guidance";
export {sources,routes,yesNo} from "./questions-v1";
export type {Route,Answers,Option} from "./questions-v1";
export type Question=LegacyQuestion&{type?:"single"|"multi"};
export const RULES_VERSION="2026-10-02.3";
export const REVIEWED_ON=knowledgeStatus.reviewedOn;
export const DRAFT_KEY="literallyglobal.eligibility.draft.v2";
const options=(v:[string,string][]):Option[]=>v.map(([value,label])=>({value,label}));
export function selectedOptions(value?:string):string[]{return value?value.split("|").filter(Boolean):[];}
export function validAnswer(question:Question,value?:string):boolean{if(typeof value!=="string"||!value)return false;const picked=question.type==="multi"?selectedOptions(value):[value];return picked.length>0&&new Set(picked).size===picked.length&&picked.every(v=>question.options.some(o=>o.value===v))&&!(picked.includes("none")&&picked.length>1)&&value===picked.join(question.type==="multi"?"|":"");}
export function toggleAnswer(question:Question,current:string|undefined,value:string){if(question.type!=="multi")return value;if(value==="none")return "none";const picked=selectedOptions(current).filter(v=>v!=="none");return question.options.map(o=>o.value).filter(v=>v===value?!picked.includes(v):picked.includes(v)).join("|");}
export const techCoreQuestions:Question[]=[
 {id:"company_type",title:"Are you working or have worked in a product-led digital technology company?",help:"Think of a company building its own digital product or platform, such as SaaS, fintech, AI or gaming. The relevance of consulting or mixed product/service work needs individual review; job title alone is not enough.",options:options([["yes","Yes, my company is product-led in digital tech"],["partial","Partially — we have some digital products but also offer services"],["no","No — I work in consulting, outsourcing, or service-only"]]),source:sources.tech},
 {id:"role_type",title:"Are you a technical or business leader/aspiring leader?",help:"Technical examples include engineers, architects, data scientists and CTOs. Business examples include product, growth and investment leadership in digital product businesses.",options:options([["tech_leader","Yes, I hold a technical role (engineer, architect, CTO, etc.)"],["biz_leader","Yes, I hold a business role in a tech company (PM, VP, C-level)"],["mid_level","I’m in a mid-level technical role with growing responsibilities"],["non_tech","My role is non-technical in a non-tech company"]]),source:sources.tech},
 {id:"talent_route",title:"Which route best describes you?",help:"Choose the level of recognition you can show. There is no automatic five-year rule for talent; promise applicants are usually earlier in their technology career.",options:options([["talent","Exceptional Talent — I have recognised leadership in tech"],["promise","Exceptional Promise — I’m an emerging leader with strong potential"],["unsure","I’m not sure which route applies to me"],["neither","I don’t think either applies to me yet"]]),source:sources.tech},
 {id:"evidence_impact",type:"multi",title:"Can you say you have done one or more of the following?",help:"Select all that apply. These examples help identify possible evidence, but their relevance, independence and significance still need review. £30,000 is not an official minimum salary for this route and earning it does not establish eligibility.",options:options([["ngo_growth","Led the growth of an NGO or tech-led initiative"],["speaking","Spoken at a high-profile event (nationally or internationally recognised)"],["awards","Received awards outside your 9–5"],["publications","Been featured in a publication for your thought leadership"],["judging","Judged the work of others outside your 9–5"],["high_salary","Earn a high salary (£30,000 and above)"],["open_source","Contributed substantially to open source"],["none","None of the above"]]),source:sources.tech},
 {id:"innovation",title:"Can you demonstrate innovation in digital technology?",help:"Use genuine product innovation as a founder or senior executive, or work in a new digital field as an employee. These are alternatives within ONE category. Revenue/accounts are relevant to business claims, not a blanket requirement for every employee.",options:options([["strong","Yes, I can provide strong evidence of innovation"],["some","I have some evidence of innovation but may need to strengthen it"],["none","I don’t have clear evidence of innovation yet"]]),source:sources.tech},
 {id:"outside_work",type:"multi",title:"What do you do outside of your 9-5?",help:"Select all that apply. These are possible examples within one category. You will be asked whether you can show independent recognition of your contribution.",options:options([["speaking","I speak at events"],["mentoring","I mentor people outside my 9–5 in a structured setting (not sponsorship)"],["writing","I have written articles/publications featured on big platforms"],["open_source","I contribute to open source"],["none","None of the above"]]),source:sources.tech},
 {id:"significant_contribution",title:"Can you demonstrate significant technical, commercial or entrepreneurial contributions?",help:"Show your own measurable impact on a product-led technology business: a key product contribution, growth, investment, strategy or entrepreneurial results.",options:options([["strong","Yes, I can evidence significant contributions with supporting documents"],["some","I have some contributions but need to package them better"],["none","I don’t have clear evidence of significant contributions yet"]]),source:sources.tech},
 {id:"academics",type:"multi",title:"Academic achievements — select all that apply",help:"A distinction alone is not the research criterion. Relevant published research or an expert-endorsed contribution can help; the quality and peer/expert recognition still need review.",options:options([["distinction","I have a distinction in my Master’s or PhD"],["published","My work has been published in academic papers"],["proof","I can provide verifiable proof of these achievements"],["expert","A research supervisor or other expert has endorsed my research contribution"],["none","None of the above"]]),source:sources.tech},
 {id:"recommendation_letters",title:"Can you provide recommendation letters?",help:"You need three established technology experts who each know your work for at least 12 months. Their letters should give different, specific examples of your achievements and potential UK contribution.",options:options([["yes_3","Yes, I have 3 suitable recommenders who can write strong letters"],["some","I have 1–2 suitable recommenders but need more"],["none","I don’t have suitable recommenders yet"]]),source:sources.techDocuments},
];
const directTitles:Record<string,string>={designScope:"What type of design work do you do?",designWork:"Have you worked regularly as a professional designer in the last 5 years?",internationalWork:"Has your design work been published, sold, distributed or exhibited internationally?",designMedia:"Has your work received at least 2 qualifying media reviews?",designExhibitions:"Has your work appeared in significant international exhibitions, publications or professional events?",designLetters:"Do you have 3 suitable people or organisations to recommend you?",designPack:"Do you have a CV and evidence of your design work from the last 5 years?",researchPath:"Which of these describes your research situation?",discipline:"Do you work in a research field covered by this route?",appointment:"Have you accepted a research or academic job at an approved UK institution?",appointmentRole:"Is research, innovation or academic leadership the main focus of your job?",recruitment:"Can your employer confirm how you were recruited?",appointmentDocs:"Can HR give you a confirmation letter and full job description?",fellowship:"Have you held an approved fellowship in the last 5 years?",fellowshipLetter:"Do you have the official letter awarding your fellowship?",funder:"Is the organisation funding your grant on UKRI’s approved list?",host:"Is your UK employer or host on the approved list?",grant:"Is your grant worth at least £30,000 and running for at least 2 years?",awardType:"Is your grant a one-off award or regularly peer-reviewed renewable award?",contract:"Will you have at least 1 year left on your work or hosting agreement?",grantTime:"Do you spend at least half your working time on qualifying research grants?",namedOnGrant:"Are you or your job title named on the grant application?",grantDocs:"Can you get the grant confirmation and an HR letter about your role?",activeResearch:"Are you currently doing research at a university, institute or business?",phd:"Do you have a PhD or equivalent research experience?",earlyCareer:"Are you still at an early stage of your research career?",ukReferee:"Do you know a recognised expert in the UK who can recommend your research?",objectiveLetter:"Can a second UK-based senior expert give an independent assessment of your work?",researchCV:"Do you have a research CV and a clear plan for your contribution in the UK?"};
function baseQuestionsFor(route:Route,a:Answers):Question[]{
 const legacy=legacyQuestionsFor(route,a);if(a.prize==="yes")return legacy;
 if(route!=="digital-technology"){
  const direct:Question[]=legacy.map(q=>({...q,title:directTitles[q.id]??q.title,help:q.id==="researchRecognition"?"Think of research impact, publications, grants, prizes or independent expert recognition. Use examples appropriate to your career stage; no fixed publication count qualifies you automatically.":q.help}));
  const examples:Question|undefined=route==="design"&&!["fashion","architecture","other"].includes(a.designScope)?{id:"design_examples",type:"multi",title:"Which of these have you achieved through your design work?",help:"Select all that apply. We’ll check the requirements for each category next; selecting several examples does not automatically satisfy multiple criteria.",options:options([["media","My design work has been reviewed in recognised media"],["awards","I have won, been nominated or shortlisted for an international design award"],["exhibitions","My work has appeared in professional exhibitions or international publications"],["international","My work has reached clients or audiences in other countries"],["none","None of the above"]]),source:sources.design}:route==="academia-research"&&["peer","unsure"].includes(a.researchPath)?{id:"research_examples",type:"multi",title:"Which research achievements can you point to?",help:"Select all that apply. Quality, your contribution and career stage matter. No publication count, grant or degree automatically proves research leadership.",options:options([["publications","I have published research in my field"],["funding","I have secured research funding"],["awards","I have received research prizes or awards"],["impact","My research has influenced practice, products or other research"],["leadership","I have led research projects or collaborations"],["none","None of the above"]]),source:sources.peer}:undefined;
  if(examples){const position=direct.findIndex(q=>q.id===(route==="design"?"designMedia":"researchRecognition"));direct.splice(Math.max(0,position),0,examples);}return direct;
 }
 const old=legacyQuestionsFor(route,{...a,track:a.talent_route==="promise"?"promise":"talent"});const q=(id:string)=>old.find(q=>q.id===id)!;
 return [...old.slice(0,2),...techCoreQuestions,{...q("recognition"),title:"Can independent evidence show that others recognised you as a tech leader or potential leader in the last 5 years?"},...(a.outside_work&&a.outside_work!=="none"?[{id:"outside_proof",title:"Can you show independent recognition of your contribution outside work?",help:"For example, evidence of structured mentoring, recognised sector contributions or significant community impact. Several activities still count as one category.",options:q("recognition").options,source:sources.tech}]:[]),...(selectedOptions(a.academics).some(v=>["published","expert"].includes(v))?[{id:"research_proof",title:"Does your research show an exceptional contribution supported by peer review or expert endorsement?",help:"A degree, distinction or publication by itself is not enough. Show the contribution, relevance to technology and independent recognition.",options:q("recognition").options,source:sources.tech}]:[]),q("techExperience"),q("techPack"),q("founder"),...(a.founder==="yes"?[q("businessProof")]:[]),q("stage")];
}
export function questionsFor(route:Route,a:Answers):Question[]{return baseQuestionsFor(route,a).map(q=>{const advice=evidenceHelp(route,q.id);return advice?{...q,help:`${q.help??""} ${advice}`.trim()}:q;});}
export function questionsForVersion(route:Route,a:Answers,version:string){return version==="2026-10-01.1"?legacyQuestionsFor(route,a):version==="2026-10-02.2"?baseQuestionsFor(route,a):questionsFor(route,a);}
