import type { EligibilityResult } from "./evaluate";

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]!));

export function reportEmail(result: EligibilityResult, dashboardUrl: string) {
  const score = result.score === null ? "Individual route review needed" : `Eligibility readiness: ${result.score}/100`;
  const improvements = result.checks.filter((check) => check.status !== "met");
  const nextSteps = improvements.length ? improvements.map((check) => `${check.label}: ${check.recommendation}`) : ["Have the actual documents reviewed against the current criteria before applying."];
  const text = ["Your LiterallyGlobal eligibility report", result.routeName, result.pathway, score, result.headline, result.summary, "Recommended next steps", ...nextSteps, result.recommendationReason, ...result.notes, `View your saved result and our services: ${dashboardUrl}`, `Rules version: ${result.rulesVersion}`, "Official guidance", ...result.sources].join("\n\n");
  const html = `<div style="background:#fbf8f1;color:#0f0a03;padding:32px;font-family:Arial,sans-serif;line-height:1.7;max-width:640px;margin:auto"><p style="font-weight:bold;letter-spacing:1px">LiterallyGlobal</p><h1 style="font-size:28px;line-height:1.2">Your talent. Your next step.</h1><p>${escapeHtml(result.routeName)} · ${escapeHtml(result.pathway)}</p><div style="background:#0f0a03;color:#fff;padding:24px;border-radius:12px"><strong style="font-size:28px;color:#f1cc74">${escapeHtml(score)}</strong><h2 style="font-size:20px">${escapeHtml(result.headline)}</h2></div><p>${escapeHtml(result.summary)}</p><h2 style="font-size:20px">Recommended next steps</h2><ul>${nextSteps.map((step) => `<li>${escapeHtml(step)}</li>`).join("")}</ul><p>${escapeHtml(result.recommendationReason)}</p>${result.notes.map((note) => `<p>${escapeHtml(note)}</p>`).join("")}<p><a href="${escapeHtml(dashboardUrl)}" style="display:inline-block;background:#c08000;color:#0f0a03;padding:14px 22px;border-radius:6px;text-decoration:none;font-weight:bold">View my result & services</a></p><p style="font-size:12px">Rules version: ${escapeHtml(result.rulesVersion)}. This is a report you requested, not a marketing subscription.</p><p>Official guidance:</p><ul>${result.sources.map((url) => `<li><a href="${escapeHtml(url)}">${escapeHtml(new URL(url).pathname.split("/").filter(Boolean).pop()!.replaceAll("-", " "))}</a></li>`).join("")}</ul></div>`;
  return { subject: "Your LiterallyGlobal eligibility score and next steps", text, html };
}
