import Link from "next/link";
import {notFound} from "next/navigation";
import {z} from "zod";
import {requireAdmin} from "@/lib/applications/access";
import {adminClient} from "@/lib/supabase/server";
import {dateLabel,userLabels} from "@/lib/admin/data";
import type {Turn,ChatReport} from "@/lib/grace-ai/schema";
export const metadata={title:"Admin · Grace AI discussion"};
export default async function Discussion({params}:{params:Promise<{id:string}>}){await requireAdmin();const{id}=await params;if(!z.uuid().safeParse(id).success)notFound();const{data:c,error}=await adminClient().from("grace_conversations").select("*").eq("id",id).maybeSingle();if(error)throw new Error("Unable to load this discussion.");if(!c)notFound();const labels=await userLabels([c.user_id]);const turns=c.turns as Turn[],report=c.report as ChatReport|null;return <><Link className="workspace-back" href="/admin/grace-ai">← Grace AI usage</Link><div className="workspace-page-heading"><div><p className="eyebrow">CLIENT DISCUSSION</p><h1>{labels[c.user_id]?.name}</h1><p>{c.route.replaceAll("-"," ")} · {turns.length} client messages · Started {dateLabel(c.created_at)}</p></div><Link className="button button-outline" href={`/admin/users/${c.user_id}`}>Client profile ↗</Link></div><div className="admin-discussion-grid"><section className="workspace-panel"><h2>Conversation transcript</h2>{!turns.length&&<p>This conversation has no saved exchanges yet.</p>}{turns.map(t=><div key={t.requestId} className="admin-chat-exchange"><small>{dateLabel(t.at)}</small><div className="chat-line from-user"><div className="chat-message"><span>Client</span><p>{t.message}</p></div></div><div className="chat-line from-grace"><span className="chat-message-avatar" aria-hidden="true">✦</span><div className="chat-message"><span>Grace AI</span><p>{t.reply}</p></div></div></div>)}</section><aside className="workspace-panel"><h2>AI-generated action plan</h2>{report?<><p>{report.summary}</p><h3>Next steps</h3><ol>{report.nextSteps.map((v,i)=><li key={i}>{v}</li>)}</ol><h3>Evidence gaps</h3><ul>{report.gaps.map((v,i)=><li key={i}>{v}</li>)}</ul><a className="button button-dark" href={`/api/grace-ai/${id}/report`}>Download discussion ↓</a></>:<p>No AI report saved yet.</p>}{c.assessment_id&&<Link className="text-link" href={`/admin/assessments/${c.assessment_id}`}>Linked eligibility score ↗</Link>}<p className="fine-print">This summary is AI-generated and separate from your personal review of the client’s request.</p></aside></div></>;}
