import { UiIcon } from "@/components/ui-icon";
import {z} from "zod";
import type { Metadata } from "next";
import Link from "next/link";
import { SignOutButton } from "@/components/dashboard/account-actions";
import { redirect } from "next/navigation";
import { Brand } from "@/components/brand";
import { adminClient,verifiedUser } from "@/lib/supabase/server";
import { isAdminEmail } from "@/lib/applications/access";
import { statusLabels } from "@/lib/applications/types";
export const metadata:Metadata={title:"Service requests",robots:{index:false,follow:false}};
export default async function AdminPage({searchParams}:{searchParams:Promise<{status?:string;service?:string;page?:string;user?:string}>}){
 const user=await verifiedUser();if(!user)redirect("/login?next=%2Fadmin");if(!isAdminEmail(user.email))return <main className="container app-page"><p className="eyebrow">TEAM ACCESS</p><h1>Sign in with your admin account.</h1><p>You’re signed in as {user.email}. This account does not have admin access. Sign out, then sign in with your authorised team email.</p><div className="report-actions"><SignOutButton/><Link className="button button-outline" href="/dashboard">Back to my dashboard</Link></div></main>;const params=await searchParams;const page=Math.min(1000,Math.max(1,Number.parseInt(params.page??"1")||1));const status=params.status&&Object.hasOwn(statusLabels,params.status)?params.status:"all";const service=["document-review","full-support"].includes(params.service??"")?params.service!:"all";const userFilter=z.uuid().safeParse(params.user).success?params.user:undefined;const db=adminClient();
 let query=db.from("service_applications").select("id,name,email,service,status,decision,created_at",{count:"exact"});if(userFilter)query=query.eq("user_id",userFilter);if(status!=="all")query=query.eq("status",status);else query=query.neq("status","draft");if(service!=="all")query=query.eq("service",service);const data=await query.order("created_at",{ascending:false}).range((page-1)*25,page*25-1);
 const pageHref=(p:number)=>`/admin/requests?${new URLSearchParams({status,service,page:String(p),...(userFilter?{user:userFilter}:{})})}`;
 return <><div className="request-heading"><div><p className="eyebrow">LITERALLYGLOBAL OPERATIONS</p><h1>Applications & reviews.</h1><p>Review documents, check confirmed payments and publish a personal verdict.</p></div><span className="request-status">{data.count??0} matching requests</span></div><form className="admin-filters">{userFilter&&<input type="hidden" name="user" value={userFilter}/>}<label className="field-label">Status<select name="status" defaultValue={status}><option value="all">All submitted requests</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field-label">Service<select name="service" defaultValue={service}><option value="all">All services</option><option value="document-review">Document review</option><option value="full-support">Full support</option></select></label><button className="button button-dark">Filter requests</button>{userFilter&&<Link href="/admin/requests">Show all users</Link>}</form>
 {data.error?<p className="form-error">The application database is not available. <Link href="/admin/setup">Open setup</Link> to connect it before accepting requests.</p>:<section className="request-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Client</th><th>Service</th><th>Status</th><th>Received</th><th>Review</th></tr></thead><tbody>{data.data?.map(a=><tr key={a.id}><td><strong>{a.name}</strong><span>{a.email}</span></td><td>{a.service==="document-review"?"Document review":"Full support"}</td><td>{statusLabels[a.status]}</td><td>{new Date(a.created_at).toLocaleDateString("en-GB")}</td><td><Link className="text-link" href={`/admin/applications/${a.id}`}>Open request <UiIcon name="arrow-up-right" /></Link></td></tr>)}</tbody></table></div>{!data.data?.length&&<p>No requests match these filters.</p>}<div className="report-actions">{page>1&&<Link className="button button-outline" href={pageHref(page-1)}>Previous</Link>}{page*25<(data.count??0)&&<Link className="button button-outline" href={pageHref(page+1)}>Next</Link>}</div></section>}</>;
}
