import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import { FullSupportContact } from "@/components/applications/full-support-contact";
import { notFound,redirect } from "next/navigation";
import { contactEmail } from "@/lib/site";
import { verifiedUser,authClient } from "@/lib/supabase/server";
import { IntakeForm } from "@/components/applications/intake-form";
export const metadata={title:"Request support"};
export default async function ServicePage({params,searchParams}:{params:Promise<{service:string}>;searchParams:Promise<{assessment?:string;conversation?:string}>}){
 const {service}=await params;if(service!=="document-review"&&service!=="full-support")notFound();const user=await verifiedUser();if(!user)redirect(`/login?next=${encodeURIComponent(`/dashboard/services/${service}`)}`);const review=service==="document-review";const chosen=await searchParams;const db=await authClient();
 const [probe,a,c]=await Promise.all([db.from("service_applications").select("id").eq("user_id",user.id).limit(1),db.from("assessments").select("id,created_at,result").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100),db.from("grace_conversations").select("id,created_at,route,report").eq("user_id",user.id).not("report","is",null).order("created_at",{ascending:false}).limit(100)]);
 return <><Link className="workspace-back" href="/dashboard/services"><UiIcon name="arrow-left" /> Services & resources</Link><div className="workspace-page-heading"><div><p className="eyebrow">{review?"MAKE EVERY DOCUMENT COUNT":"LET’S BUILD YOUR APPLICATION"}</p><h1>{review?"Document review":"Apply for full support"}</h1><p>{review?"Share your draft and get clear, actionable feedback.":"Tell us about your experience. Grace will review your fit before you commit."}</p></div><span className="workspace-price">{review?"£1,000":"£2,500"}<small>{review?"Instalment payments available: 2 × £500":"Instalment payments available · subject to Grace’s review"}</small></span></div>{!review&&<FullSupportContact/>}<div className="workspace-intake-grid"><section className="workspace-panel">{probe.error?<div className="workspace-empty"><h2>Let’s arrange your support.</h2><p>Online applications are being prepared. Contact us to discuss your request.</p><a className="button button-gold" href={`mailto:${contactEmail}?subject=${encodeURIComponent(review?"Document review enquiry":"Full support enquiry")}`}>Contact LiterallyGlobal <UiIcon name="arrow-up-right" /></a></div>:<>{!review&&(a.error||c.error)&&<p className="form-notice">Some saved reports could not be loaded. You can refresh or continue with an available report.</p>}<IntakeForm accountId={user.id} service={service} name={typeof user.user_metadata?.full_name==="string"?user.user_metadata.full_name:""} email={user.email!} assessments={a.data??[]} conversations={c.data??[]} preferredAssessment={chosen.assessment} preferredConversation={chosen.conversation}/></>}</section><aside className="workspace-panel intake-explainer"><p className="eyebrow">WHAT HAPPENS NEXT</p><ol><li><strong>{review?"Share your documents":"Share your starting point"}</strong><p>{review?"Use a private Drive folder or upload your files.":"Attach your eligibility check or an existing saved discussion report."}</p></li><li><strong>{review?"Choose how to pay":"Grace reviews your fit"}</strong><p>{review?"Pay once, or make two separate £500 payments.":"See her personal verdict and recommended next steps here."}</p></li><li><strong>Keep everything together</strong><p>Find your request, documents and feedback under My requests.</p></li></ol><Link className="text-link" href="/dashboard/requests">View my requests <UiIcon name="arrow-up-right" /></Link></aside></div></>;
}
