import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import type { Application,ApplicationFile,Payment } from "@/lib/applications/types";
import { statusLabels } from "@/lib/applications/types";
import { supportFit } from "@/lib/applications/access";
import { ApplicationActions,AdditionalFiles } from "./application-actions";
export function ApplicationDetail({application:a,files,payments,admin=false}:{application:Application;files:ApplicationFile[];payments:Payment[];admin?:boolean}){
 const paid=payments.filter((p)=>p.status==="paid").reduce((sum,p)=>sum+p.amount,0);const refunded=payments.some((p)=>p.status==="refunded");const fit=supportFit(a.readiness);
 return <><div className="request-heading"><div><p className="eyebrow">{a.service==="document-review"?"DOCUMENT REVIEW":"FULL SUPPORT"}</p><h1>{admin?a.name:"Your request"}</h1><p>Submitted details · {new Date(a.created_at).toLocaleDateString("en-GB")}</p></div><span className="request-status">{statusLabels[a.status]??a.status}</span></div>
 <div className="request-grid"><section className="request-card"><h2>Your details</h2><dl className="detail-list"><dt>Name</dt><dd>{a.name}</dd><dt>Email</dt><dd><a href={`mailto:${a.email}`}>{a.email}</a></dd><dt>WhatsApp</dt><dd>{admin?<a href={`https://wa.me/${a.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">{a.whatsapp} <UiIcon name="arrow-up-right" /></a>:a.whatsapp}</dd></dl>{a.notes&&<><h3>Additional information</h3><p className="preserve-lines">{a.notes}</p></>}<h3>Documents</h3>{a.drive_url&&<a className="text-link" href={a.drive_url} target="_blank" rel="noreferrer">Open Drive folder <UiIcon name="arrow-up-right" /></a>}<ul className="document-list">{files.map((file)=><li key={file.id}><a href={`/api/files/${file.id}`}>{file.name} <span><UiIcon name="arrow-down" /></span></a><small>{(file.byte_size/1024/1024).toFixed(1)} MB</small></li>)}</ul>{!a.drive_url&&!files.length&&<p>No documents attached yet.</p>}{a.status==="draft"&&!admin&&<AdditionalFiles id={a.id}/>}</section>
 <div><section className="request-card"><p className="eyebrow">GRACE’S VERDICT</p><h2>{a.decision==="pending"?"Awaiting Grace’s review":a.decision==="suitable"?"A good fit for support":a.decision==="build_evidence"?"Build your evidence first":"Let’s discuss your route"}</h2>{a.verdict?<p className="preserve-lines">{a.verdict}</p>:<p>Grace has not reviewed this request yet. Her personal recommendation and next steps will appear here.</p>}{a.verdict&&<a className="button button-outline" href={`/api/applications/${a.id}/report`}>Download Grace’s verdict <UiIcon name="arrow-down" /></a>}</section>
 {a.service==="document-review"?<section className="request-card"><p className="eyebrow">PAYMENT</p><h2>{refunded?"Payment needs review":paid>=100000?"Paid in full":paid?"Your second payment":"Choose your next step"}</h2><p>{a.payment_plan==="once"?"One payment of £1,000":"Two separate payments of £500 · £1,000 total"}</p><dl className="payment-summary"><dt>Confirmed payments</dt><dd>£{(paid/100).toLocaleString("en-GB")}</dd><dt>Balance</dt><dd>£{(Math.max(0,100000-paid)/100).toLocaleString("en-GB")}</dd></dl>{!admin&&<ApplicationActions id={a.id} draft={a.status==="draft"} paymentLabel={a.status!=="draft"&&!refunded&&paid<100000?(a.payment_plan==="once"?"Pay £1,000 securely":paid?"Pay the remaining £500":"Pay the first £500"):undefined}/>}<p className="fine-print">Payment is confirmed after Stripe reports a successful charge. Returning from checkout alone does not mark this request as paid.</p></section>:<section className="request-card"><p className="eyebrow">INITIAL READINESS</p><h2>{fit.title}</h2><p>{fit.text}</p>{a.readiness&&<p className="readiness-number">{a.readiness.score===null?"Pathway review":`${a.readiness.score}/100`}<span>{a.readiness.routeName}</span></p>}{a.assessment_id&&<a className="text-link" href={`/api/assessments/${a.assessment_id}/report`}>Download score & next steps <UiIcon name="arrow-down" /></a>}{a.conversation_id&&<a className="text-link" href={`/api/grace-ai/${a.conversation_id}/report`}>Download Grace AI discussion <UiIcon name="arrow-down" /></a>}<p className="fine-print">The initial assessment is separate from Grace’s personal verdict above. No full-support payment is collected before review.</p>{!admin&&a.status==="draft"&&<ApplicationActions id={a.id} draft/>}<Link className="text-link" href="/dashboard/eligibility">Take a new eligibility check <UiIcon name="arrow-up-right" /></Link></section>}
 </div></div></>;
}
