"use client";
import Link from "next/link";
import { useEffect,useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { postJson } from "@/lib/eligibility/draft";
import { intakeSchema, MAX_FILES, MAX_FILE_BYTES, MAX_TOTAL_BYTES,type IntakeService } from "@/lib/applications/schema";
import type { EligibilityResult } from "@/lib/eligibility/evaluate";
export type ReportChoice={id:string;created_at:string;result:EligibilityResult};
export type ConversationChoice={id:string;created_at:string;route:string;report:{summary:string}|null};
export function IntakeForm({service,name,email,assessments,conversations,accountId,preferredAssessment,preferredConversation}:{accountId?:string;preferredAssessment?:string;preferredConversation?:string;service:IntakeService;name:string;email:string;assessments:ReportChoice[];conversations:ConversationChoice[]}){
 const router=useRouter();const [fullName,setName]=useState(name),[phone,setPhone]=useState(""),[notes,setNotes]=useState(""),[method,setMethod]=useState<"drive"|"upload">("drive"),[drive,setDrive]=useState(""),[plan,setPlan]=useState<"once"|"twice">("once"),[consent,setConsent]=useState(false);
 const [assessment,setAssessment]=useState(assessments.find(a=>a.id===preferredAssessment)?.id??assessments[0]?.id??""),[conversation,setConversation]=useState(conversations.find(c=>c.id===preferredConversation)?.id??"");
 const [files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState(""),[savedId,setSavedId]=useState<string|null>(null);
 const [submissionId,setSubmissionId]=useState(()=>crypto.randomUUID());const [uploaded,setUploaded]=useState<string[]>([]);
 const storageKey=`literallyglobal.intake.${accountId??email}.${service}`;
 const [loaded,setLoaded]=useState(false),[restored,setRestored]=useState(false);
 useEffect(()=>{try{const raw=sessionStorage.getItem(storageKey);if(raw){const v=JSON.parse(raw);if(Date.now()-v.at<86400000){setName(typeof v.name==="string"?v.name:name);setPhone(typeof v.phone==="string"?v.phone:"");setNotes(typeof v.notes==="string"?v.notes:"");setDrive(typeof v.drive==="string"?v.drive:"");setMethod(v.method==="upload"?"upload":"drive");setPlan(v.plan==="twice"?"twice":"once");if(v.submissionId)setSubmissionId(v.submissionId);if(!preferredAssessment&&assessments.some(a=>a.id===v.assessment))setAssessment(v.assessment);if(!preferredConversation&&conversations.some(c=>c.id===v.conversation))setConversation(v.conversation);setRestored(true);}else sessionStorage.removeItem(storageKey);}}catch{/* The form remains usable if temporary storage is unavailable. */}setLoaded(true);},[storageKey]);
 useEffect(()=>{if(!loaded||savedId)return;try{sessionStorage.setItem(storageKey,JSON.stringify({at:Date.now(),submissionId,name:fullName,phone,notes,drive,method,plan,assessment,conversation}));}catch{/* Optional tab-only draft storage. */}},[loaded,savedId,storageKey,submissionId,fullName,phone,notes,drive,method,plan,assessment,conversation]);
 const isReview=service==="document-review";const selected=assessments.find((a)=>a.id===assessment);
 async function submit(event:FormEvent){event.preventDefault();setError("");const parsed=intakeSchema.safeParse({submissionId,service,name:fullName,email,whatsapp:phone,notes,driveUrl:drive,documentMethod:method,paymentPlan:isReview?plan:null,assessmentId:assessment||null,conversationId:conversation||null,consent});
 if(!parsed.success){setError(parsed.error.issues[0]?.message??"Check your details.");return;}
 if(isReview&&method==="upload"&&!files.length){setError("Choose the documents you want reviewed, or use a Drive folder.");return;}
 if(files.length>MAX_FILES||files.some((f)=>f.size>MAX_FILE_BYTES)||files.reduce((n,f)=>n+f.size,0)>MAX_TOTAL_BYTES){setError("Use up to 10 files, 10 MB each and 50 MB in total.");return;}
 setBusy(true);let id=savedId;try{
  setProgress("Saving your details…");if(!id){const saved=await postJson<{id:string}>("/api/applications",parsed.data);id=saved.id;setSavedId(id);try{sessionStorage.removeItem(storageKey);}catch{}}
  if(method==="upload")for(const file of files){const key=`${file.name}:${file.size}:${file.lastModified}`;if(uploaded.includes(key))continue;setProgress(`Uploading ${file.name}…`);const body=new FormData();body.append("file",file);const response=await fetch(`/api/applications/${id}/files`,{method:"POST",body});const result=await response.json();if(!response.ok)throw new Error(result.error??"Upload failed.");setUploaded((old)=>[...old,key]);}
  setProgress("Submitting your request…");await postJson(`/api/applications/${id}/submit`,{});router.push(`/dashboard/requests/${id}`);router.refresh();
 }catch(caught){setError(caught instanceof Error?caught.message:"We couldn’t submit your request. Please retry.");}finally{setBusy(false);setProgress("");}}
 return <form className="intake-form" onSubmit={submit}>
  {restored&&<p className="draft-notice" role="status">Your draft was restored. {method==="upload"?"Please reselect any files you want to upload.":"You can pick up where you left off."}</p>}
  <fieldset disabled={busy||Boolean(savedId)} className="plain-fieldset"><div className="form-columns"><label className="field-label">Full name<input value={fullName} onChange={(e)=>setName(e.target.value)} required maxLength={100} autoComplete="name"/></label><label className="field-label">Verified email<input value={email} readOnly type="email" autoComplete="email"/></label></div>
  <label className="field-label">WhatsApp phone number<input value={phone} onChange={(e)=>setPhone(e.target.value)} type="tel" placeholder="+44 7700 900000" autoComplete="tel" required maxLength={30}/><span className="field-help">Include your country code. We’ll use this to communicate about your request.</span></label>
  {!isReview&&<div className="support-readiness"><h3>Start with your readiness report</h3><p>Full support is for professionals who already have achievements and evidence to build on. Attach your checker result. If you already have a saved Grace AI report, you can also include it. Grace reviews the fit before you commit.</p><div className="report-actions"><Link className="button button-outline" href="/dashboard/eligibility">Check my eligibility</Link><span className="fine-print">Grace AI · Coming soon</span></div>
   <label className="field-label">Eligibility assessment<select value={assessment} onChange={(e)=>setAssessment(e.target.value)}><option value="">Choose your eligibility report</option>{assessments.map((a)=><option key={a.id} value={a.id}>{a.result.routeName} · {a.result.score??"Pathway review"}{a.result.score!==null?"/100":""} · {new Date(a.created_at).toLocaleDateString("en-GB")}</option>)}</select></label>
   {selected&&<div className="readiness-preview"><strong>{selected.result.headline}</strong><p>{selected.result.checks.filter((c)=>c.status!=="met").length} checklist items need attention or clarification.</p><a className="text-link" href={`/api/assessments/${selected.id}/report`}>Download score & next steps ↓</a></div>}
   <label className="field-label">Saved Grace AI conversation (optional)<select value={conversation} onChange={(e)=>setConversation(e.target.value)}><option value="">No conversation attached</option>{conversations.filter((c)=>c.report).map((c)=><option key={c.id} value={c.id}>{c.route.replaceAll("-"," ")} · {new Date(c.created_at).toLocaleDateString("en-GB")}</option>)}</select></label>{conversation&&<a className="text-link" href={`/api/grace-ai/${conversation}/report`}>Download Grace AI discussion report ↓</a>}
  </div>}
  <h3>{isReview?"Your documents":"Supporting documents (optional)"}</h3><div className="document-method"><label className={method==="drive"?"selected":""}><input type="radio" name="method" checked={method==="drive"} onChange={()=>{setMethod("drive");setFiles([]);}}/>Google Drive folder <span>Recommended</span></label><label className={method==="upload"?"selected":""}><input type="radio" name="method" checked={method==="upload"} onChange={()=>{setMethod("upload");setDrive("");}}/>Upload documents</label></div>
  {/* Separate keys prevent React from reusing the controlled URL input as an uncontrolled file picker. */}
  {method==="drive"?<label key="drive-folder" className="field-label">Drive folder link<input type="url" placeholder="https://drive.google.com/drive/folders/…" value={drive} onChange={(e)=>setDrive(e.target.value)} required={isReview} maxLength={1000}/><span className="field-help">Share the folder with graceolayinka22@gmail.com as a viewer. You do not need to make it public.</span></label>:<label key="document-upload" className="upload-zone">Choose your documents<input type="file" accept=".pdf,.docx,.png,.jpg,.jpeg" multiple onChange={(e)=>setFiles(Array.from(e.target.files??[]))}/><span>PDF, DOCX, PNG or JPG. Up to 10 files, 10 MB each, 50 MB total.</span>{files.map((file,i)=><span key={`${file.name}-${i}`}>{file.name} · {(file.size/1024/1024).toFixed(1)} MB</span>)}</label>}
  <label className="field-label">Anything you’d like us to know?<textarea rows={5} value={notes} onChange={(e)=>setNotes(e.target.value)} maxLength={6000} placeholder="Your route, timeline, questions, or areas you’d like us to focus on."/></label>
  {isReview&&<fieldset className="payment-options"><legend>How would you like to pay?</legend><label className={plan==="once"?"selected":""}><input type="radio" name="plan" checked={plan==="once"} onChange={()=>setPlan("once")}/><strong>Pay once</strong><span>£1,000</span></label><label className={plan==="twice"?"selected":""}><input type="radio" name="plan" checked={plan==="twice"} onChange={()=>setPlan("twice")}/><strong>Two payments</strong><span>£500 + £500 · £1,000 total</span></label><p className="fine-print">Submit your form first, then pay securely. The second payment is made separately from your request page; it is not an automatic subscription.</p></fieldset>}
  <label className="consent-label"><input type="checkbox" checked={consent} onChange={(e)=>setConsent(e.target.checked)} required/><span>I agree to LiterallyGlobal using these details and documents to handle my request and contact me by email or WhatsApp. I’ve read the <Link href="/privacy" target="_blank">privacy notice</Link>.</span></label></fieldset>
  {savedId&&<p className="fine-print">Your details are saved. Retry to finish uploading or submitting, or <Link href={`/dashboard/requests/${savedId}`}>open your saved request</Link>.</p>}
  {error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-gold full-width" disabled={busy||(!isReview&&!assessment&&!conversation)}>{busy?progress:isReview?"Submit & continue to payment":"Send my application for Grace’s review"}<span aria-hidden="true">↗</span></button>
  {!isReview&&<p className="fine-print">No payment is collected at this stage. A checker score or AI conversation is an initial assessment, not a personal verdict from Grace.</p>}
 </form>;
}
