import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import {z} from "zod";
import {requireAdmin} from "@/lib/applications/access";
import {adminClient} from "@/lib/supabase/server";
import {dateLabel,pageNumber,userLabels} from "@/lib/admin/data";
import {routes} from "@/lib/eligibility/questions";
export const metadata={title:"Admin · Grace AI usage"};
export default async function AIUsage({searchParams}:{searchParams:Promise<{page?:string;route?:string;user?:string}>}){await requireAdmin();const p=await searchParams,page=pageNumber(p.page);const route=routes.some(r=>r.id===p.route)?p.route!:"all",user=z.uuid().safeParse(p.user).success?p.user:undefined;const db=adminClient();let query=db.from("grace_conversations").select("id,user_id,route,turns,report,created_at,updated_at",{count:"exact"});if(user)query=query.eq("user_id",user);if(route!=="all")query=query.eq("route",route);const{data,error,count}=await query.order("updated_at",{ascending:false}).range((page-1)*20,page*20-1);const labels=await userLabels((data??[]).map(c=>c.user_id));const href=(n:number)=>`/admin/grace-ai?${new URLSearchParams({page:String(n),route,...(user?{user}:{})})}`;
 return <><div className="workspace-page-heading"><div><p className="eyebrow">SEE WHAT CLIENTS NEED HELP WITH</p><h1>Grace AI usage</h1><p>Explore conversations, client questions and the guidance they received.</p></div><span className="request-status">{error?"Unavailable":`${count??0} conversations`}</span></div><form className="workspace-filters">{user&&<input name="user" type="hidden" value={user}/>}<label>Route<select name="route" defaultValue={route}><option value="all">All routes</option>{routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="button button-outline">Filter conversations</button>{user&&<><Link href={`/admin/users/${user}`} className="text-link">Client profile</Link><Link href="/admin/grace-ai" className="text-link">Show all users</Link></>}</form><section className="workspace-panel">{error?<p className="form-error">Conversation activity is unavailable. <Link href="/admin/setup">Check your setup</Link>.</p>:<><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Client</th><th>Route / latest question</th><th>Messages</th><th>Last activity</th><th>Discussion</th></tr></thead><tbody>{data?.map(c=>{const turns=Array.isArray(c.turns)?c.turns:[];return <tr key={c.id}><td><Link href={`/admin/users/${c.user_id}`}><strong>{labels[c.user_id]?.name}</strong><span>{labels[c.user_id]?.email}</span></Link></td><td>{routes.find(r=>r.id===c.route)?.name}<span>{turns.at(-1)?.message?.slice(0,120)??"Started — no completed exchange yet"}</span></td><td><strong>{turns.length} client messages</strong><span>{turns.length} AI replies · {c.report?"Report available":"No report yet"}</span></td><td>{dateLabel(c.updated_at)}</td><td><Link href={`/admin/grace-ai/${c.id}`}>Read conversation <UiIcon name="arrow-up-right" /></Link></td></tr>;})}</tbody></table></div>{!data?.length&&<p>No conversations match these filters.</p>}<div className="workspace-pagination">{page>1&&<Link href={href(page-1)}><UiIcon name="arrow-left" /> Previous</Link>}<span>Page {page}</span>{page*20<(count??0)&&<Link href={href(page+1)}>Next <UiIcon name="arrow-right" /></Link>}</div></>}</section><p className="fine-print">Message counts reflect successfully saved exchanges. They do not include unsent drafts or provider requests that failed before a reply was saved.</p></>;
}
