"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type { Application } from "@/lib/applications/types";
import { statusLabels } from "@/lib/applications/types";
export function ReviewForm({application:a}:{application:Application}){
 const [status,setStatus]=useState(a.status),[decision,setDecision]=useState(a.decision),[verdict,setVerdict]=useState(a.verdict),[notes,setNotes]=useState(a.internal_notes??""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);const router=useRouter();
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setSaved(false);try{const response=await fetch(`/api/admin/applications/${a.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,decision,verdict,internalNotes:notes,version:a.version})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not save review.");setSaved(true);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to save.");}finally{setBusy(false);}}
 return <form className="request-card admin-review" onSubmit={submit}><p className="eyebrow">TEAM REVIEW</p><h2>Publish Grace’s verdict.</h2><p>The verdict and status appear in the client’s account as soon as you save. Internal notes remain visible to the team only.</p><fieldset disabled={busy||a.status==="draft"}><div className="form-columns"><label className="field-label">Application status<select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(statusLabels).filter(([k])=>k!=="draft").map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field-label">Recommendation<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="pending">Awaiting review</option><option value="suitable">Suitable for support</option><option value="build_evidence">Build evidence first</option><option value="consultation">Recommend consultation</option></select></label></div><label className="field-label">Grace’s verdict and action plan — visible to client<textarea rows={7} required={decision!=="pending"} minLength={decision!=="pending"?10:0} maxLength={6000} value={verdict} onChange={e=>setVerdict(e.target.value)}/></label><label className="field-label">Internal notes — team only<textarea rows={4} maxLength={6000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button button-gold">{busy?"Saving…":"Save review & update client dashboard"}</button></fieldset>{a.status==="draft"&&<p className="fine-print">This client has not submitted their request yet.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{saved&&<p className="form-notice" role="status">Review saved. The client can now see it in their account.</p>}</form>;
}
