import { UiIcon } from "@/components/ui-icon";
import Link from "next/link";
import {requireAdmin} from "@/lib/applications/access";
import {adminClient} from "@/lib/supabase/server";
import {dateLabel,userLabels} from "@/lib/admin/data";
export const metadata={title:"Admin overview"};
export default async function AdminOverview(){await requireAdmin();const db=adminClient();const since=new Date(Date.now()-7*86400000).toISOString();const[users,requests,checks,chats,recent,chatWeek]=await Promise.all([db.auth.admin.listUsers({page:1,perPage:1}),db.from("service_applications").select("id",{count:"exact",head:true}).neq("status","draft"),db.from("assessments").select("id",{count:"exact",head:true}),db.from("grace_conversations").select("id",{count:"exact",head:true}),db.from("assessments").select("id,user_id,result,created_at").order("created_at",{ascending:false}).limit(5),db.from("grace_conversations").select("id",{count:"exact",head:true}).gte("updated_at",since)]);const labels=await userLabels((recent.data??[]).map(a=>a.user_id));
 const cards=[{label:"Registered users",count:users.error?null:users.data.total,href:"/admin/users",help:"Accounts & individual activity"},{label:"Submitted requests",count:requests.error?null:requests.count,href:"/admin/requests",help:"Document review & full support"},{label:"Eligibility checks",count:checks.error?null:checks.count,href:"/admin/assessments",help:"Answers, scores & recommendations"},{label:"Grace AI discussions",count:chats.error?null:chats.count,href:"/admin/grace-ai",help:chatWeek.error?"Conversation history":`${chatWeek.count??0} active in the last 7 days`}];
 return <><div className="workspace-page-heading"><div><p className="eyebrow">LITERALLYGLOBAL OPERATIONS</p><h1>Your business at a glance.</h1><p>Understand your users, follow their progress and see where they need support.</p></div><Link className="button button-outline" href="/admin/setup">Connection status <UiIcon name="arrow-up-right" /></Link></div><section className="workspace-stats">{cards.map(c=><Link href={c.href} key={c.label}><span>{c.label}</span><strong>{c.count??"—"}</strong><small>{c.help} <UiIcon name="arrow-up-right" /></small></Link>)}</section>{cards.some(c=>c.count==null)&&<p className="form-notice">Some activity could not be loaded. <Link href="/admin/setup">Check your connections</Link>. Unavailable counts are shown as a dash.</p>}<section className="workspace-panel"><div className="panel-heading"><h2>Recent eligibility checks</h2><Link className="text-link" href="/admin/assessments">View all <UiIcon name="arrow-up-right" /></Link></div>{recent.error?<p>Eligibility activity is currently unavailable.</p>:recent.data?.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Client</th><th>Route</th><th>Readiness</th><th>Completed</th><th>Report</th></tr></thead><tbody>{recent.data.map(a=><tr key={a.id}><td><Link href={`/admin/users/${a.user_id}`}><strong>{labels[a.user_id]?.name}</strong><span>{labels[a.user_id]?.email}</span></Link></td><td>{a.result.routeName}</td><td><strong>{a.result.score===null?"Pathway review":`${a.result.score}/100`}</strong><span>{a.result.headline}</span></td><td>{dateLabel(a.created_at)}</td><td><Link href={`/admin/assessments/${a.id}`}>Open <UiIcon name="arrow-up-right" /></Link></td></tr>)}</tbody></table></div>:<p>Completed assessments will appear here once clients save their results.</p>}</section><div className="workspace-overview-grid"><section className="workspace-panel"><h2>Follow the full client journey.</h2><p>Open a user’s profile to see their requests, eligibility checks and Grace AI discussions together.</p><Link className="button button-dark" href="/admin/users">Browse users <UiIcon name="arrow-up-right" /></Link></section><section className="workspace-panel"><h2>Understand what people ask.</h2><p>See the route, message count and timing of each AI conversation, then open its transcript and generated plan.</p><Link className="button button-outline" href="/admin/grace-ai">Explore Grace AI usage <UiIcon name="arrow-up-right" /></Link></section></div></>;
}
